---

- name: create Kibana user
  user:
    name={{ kibana_user }}
    system=yes
    shell=/bin/false
    home=/var/lib/{{ kibana_user }}
    state=present

- name: download Kibana
  get_url:
    url=https://download.elastic.co/kibana/kibana/kibana-{{ kibana_version }}-linux-x64.tar.gz
    dest=/tmp/kibana-{{ kibana_version }}-linux-x64.tar.gz
    mode=0440

- name: uncompress and install Kibana
  unarchive:
    src=/tmp/kibana-{{ kibana_version }}-linux-x64.tar.gz
    dest={{ kibana_install_dir }}
    creates={{ kibana_install_dir }}/kibana-{{ kibana_version }}-linux-x64
    mode=0755
    owner={{ kibana_user }}
    group={{ kibana_group }}
    copy=no

- name: copy kibana init file
  template:
    src=kibana.init.j2
    dest=/etc/init.d/kibana
    mode=755
  notify:
  - restart kibana

- name: configure kibana
  template:
    src=kibana.yml.j2
    dest={{ kibana_install_dir }}/kibana-{{ kibana_version }}-linux-x64/config/kibana.yml
  notify: restart kibana

- name: touch log file if it does not exist
  command: touch {{ kibana_log }}
           creates={{ kibana_log }}

- name: set log file permissions
  file: path={{ kibana_log }} owner={{ kibana_user }} group={{ kibana_group }} mode=0644

- name: configure Kibana log rotation
  template: src=logrotate_kibana.j2 dest=/etc/logrotate.d/kibana

- name: enable kibana service
  service: name=kibana enabled=yes state=started

# install Sense plugin
- include: sense-plugin.yml

# install Marvel plugin
- include: marvel-plugin.yml