---

- name: install Marvel plugin
  shell: bin/kibana plugin --install elasticsearch/marvel/latest
    chdir={{ kibana_install_dir }}/kibana-{{ kibana_version }}-linux-x64/
  register: marvel_plugin_installed
  changed_when: "'Installed' in marvel_plugin_installed.stdout"
  failed_when: "marvel_plugin_installed.rc != 0 and marvel_plugin_installed.stderr.find('marvel already exists, please remove before installing a new version') == -1"

# Fix permissions
- file: >
    path="{{ kibana_install_dir }}/kibana-{{ kibana_version }}-linux-x64/installedPlugins/marvel" state=directory
    owner={{ kibana_user }} group={{ kibana_group }}
    recurse=yes
  sudo: true
